# Generated by Django 3.2.9 on 2022-01-28 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default=' ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('activate_by_admin', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=230)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('proche_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('marital_status', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=230, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departments')),
            ],
        ),
        
        migrations.CreateModel(
            name='ServiceReceptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('activate_by_admin', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=230)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=200)),
                ('ward_no', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalReceptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('activate_by_admin', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=230)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
       
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=200, null=True)),
                ('pulse', models.CharField(blank=True, max_length=200, null=True)),
                ('breathing_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.CharField(blank=True, max_length=200, null=True)),
                ('blood_sugar', models.CharField(blank=True, max_length=200, null=True)),
                ('temperature', models.CharField(blank=True, max_length=200, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departments')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients')),
                ('service_receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.servicereceptionist')),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('activate_by_admin', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=230)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointment', models.DateField()),
                ('hour_appointment', models.CharField(default='00:00', max_length=9999999999)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departments')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients')),
                ('service_receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.servicereceptionist')),
            ],
        ),
    ]
