# Generated by Django 3.2.9 on 2022-01-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='gender',
            field=models.CharField(choices=[('MAN', 'MAN'), ('WOMAN', 'WOMAN')], max_length=5),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('MAN', 'MAN'), ('WOMAN', 'WOMAN')], max_length=5),
        ),
        migrations.AlterField(
            model_name='principalreceptionist',
            name='gender',
            field=models.CharField(choices=[('MAN', 'MAN'), ('WOMAN', 'WOMAN')], max_length=5),
        ),
        migrations.AlterField(
            model_name='servicereceptionist',
            name='gender',
            field=models.CharField(choices=[('MAN', 'MAN'), ('WOMAN', 'WOMAN')], max_length=5),
        ),
    ]
