# Generated by Django 3.2.9 on 2022-01-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_servicereceptionist_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='phone',
            field=models.BigIntegerField(default=655433221),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='phone',
            field=models.BigIntegerField(default=655433221),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='principalreceptionist',
            name='phone',
            field=models.BigIntegerField(default=675454332),
            preserve_default=False,
        ),
    ]
