# Generated by Django 3.2.9 on 2022-01-30 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20220129_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_motif', models.CharField(max_length=999999, unique=True)),
                ('montant', models.CharField(max_length=999999)),
            ],
        ),
        migrations.AlterField(
            model_name='cashier',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        
        migrations.AlterField(
            model_name='principalreceptionist',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicereceptionist',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=999999)),
                ('payment_method', models.CharField(max_length=999999)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.cashier')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departments')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.paymentmotif')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients')),
            ],
        ),
    ]
