# Generated by Django 3.2.9 on 2022-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_montant_paymentmotif_amount_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='state',
            field=models.CharField(default='Non consulté', max_length=9999999999),
        ),
    ]
