# Generated by Django 3.2.9 on 2022-02-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_prescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departments')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients')),
            ],
        ),
    ]
