# Generated by Django 3.2.9 on 2022-02-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_patientdepartments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='department',
        ),
        migrations.AddField(
            model_name='patients',
            name='principal_receptionist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.principalreceptionist'),
        ),
    ]
