# Generated by Django 3.2.9 on 2022-02-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20220224_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='service_receptionist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.servicereceptionist'),
        ),
    ]
