# Generated by Django 3.2.9 on 2022-02-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_parameters_service_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], default='SINGLE', max_length=8),
        ),
        migrations.AddField(
            model_name='doctors',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], default='SINGLE', max_length=8),
        ),
        migrations.AddField(
            model_name='principalreceptionist',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], default='SINGLE', max_length=8),
        ),
        migrations.AddField(
            model_name='servicereceptionist',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], default='SINGLE', max_length=8),
        ),
    ]
