# Generated by Django 3.2.9 on 2022-03-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20220228_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], default='SINGLE', max_length=8),
        ),
    ]
