# Generated by Django 3.2.9 on 2022-03-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_principalreceptionist_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptions',
            name='prescription',
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='drug_prescription',
            field=models.TextField(max_length=999999, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='examinations',
            field=models.TextField(max_length=999999, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='recommendations',
            field=models.TextField(max_length=999999, null=True),
        ),
    ]
