# Generated by Django 3.2.9 on 2022-03-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_paymentmotif_durée_en_jours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='service_receptionist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.servicereceptionist'),
        ),
    ]
