# Generated by Django 3.1.6 on 2022-03-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_appointments_service_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='state',
            field=models.CharField(default='Not consulted', max_length=9999999999),
        ),
    ]
