# Generated by Django 3.2.9 on 2022-03-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_appointments_service_receptionist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='proche_phone',
            new_name='emergency_phone',
        ),
    ]
